services:
  app:
    image: toyama4649/kirameki-php-cli:latest
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        source: user
        target: /root
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:9
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysql", "-uroot", "-proot", "-e", "SELECT 1"]
      start_period: 5s
      interval: 5s
volumes:
  user:
