services:
  app:
    image: toyama4649/kirameki-php-cli:latest
    environment:
      PHP_ZEND_ASSERTIONS: "-1"
      TZ: "Asia/Tokyo"
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        source: user
        target: /root
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:9
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - "./docker/mysql/files/etc/mysql/my.conf:/etc/mysql/my.cnf"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      start_period: 5s
      interval: 5s
volumes:
  user:
